keys:
  - &users: # public user gpg fingerprints
    - &chris DB9ADBBE6FBD1F0E694AF25D012321D46E090E61
  - &hosts: # public age host keys
    - &thinkpad age1xdp3rwum0jjunk9l4vgp9k8w3fm685z70u0fx84gxpgj5mjdhg3s77v4mp
    - &vm1 age1h07t74u3eq9zsddn0pruzwmjpuuawtnpr7x722nfsen2qu0ege5qdje5xu 
    - &aspen age1zeavlllujxttwxegdtae4yqmj5gc4prp8xdu8m9xwn49qml4s3eq2c2ck6 

creation_rules: # when sops creates/edits a secrets.yaml file it encrypts using both gpg and age public keys and one or the other corresponding private keys will be required to decrypt
  - path_regex: secrets.(yaml|json|env|ini)$ 
    key_groups:
      - pgp:
        - *chris 
        age:
        - *thinkpad
        - *vm1
        - *aspen

# run 'sops updatekeys /home/chris/nixos-configs/secrets.yaml' on the encrypted secrets file to update with new user or host encryption keys when added above