keys:
  - &users:
    - &chris DB9ADBBE6FBD1F0E694AF25D012321D46E090E61 # public gpg key fingerprint
  - &hosts:
    - &thinkpad age1863w249676ln7c7gsv945hrlef26fumrkr3ynze066jkz4eyxp0sewdzkx # public age key (converted from ssh public ed25519 key in /etc/ssh)

creation_rules: # when sops creates/edits a secrets.yaml file it encrypts using both gpg and age public keys and one or the other corresponding private keys will be required to decrypt
  - path_regex: secrets.(yaml|json|env|ini)$ 
    key_groups:
      - pgp:
        - *chris 
        age:
        - *thinkpad