keys:
  - &users:
    - &chris age1v2j6pfycg686a9zvgwjzfu5p9v9wfxwrxjgg2er09u7q6dxqly4qhefnff # chris public age key
  - &hosts:
    - &thinkpad age18a64qgesyjx6wns78rdxu3rfp2pjyattpac05wt0cuny3qcqfqwq43x778 # thinkpad public age key (converted from ssh public ed25519 key in /etc/ssh)

creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *chris
      - *thinkpad