keys:
  - &users:
    - &chris DB9ADBBE6FBD1F0E694AF25D012321D46E090E61 # public gpg key fingerprint

creation_rules:
  - path_regex: secrets.(yaml|json|env|ini)$ 
    key_groups:
      - pgp:
        - *chris 