keys:
  - &users:
    - &chris DB9ADBBE6FBD1F0E694AF25D012321D46E090E61 # public gpg key fingerprint
  - &hosts:
    - &thinkpad age1gyjvseqm77eqvuqah88d7j3a3acne069q4smcdcdxqec3df223rs47e7al # public age key (converted from ssh public ed25519 key in /etc/ssh using 'nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'')

creation_rules: # when sops creates/edits a secrets.yaml file it encrypts using both gpg and age public keys and one or the other corresponding private keys will be required to decrypt
  - path_regex: secrets.(yaml|json|env|ini)$ 
    key_groups:
      - pgp:
        - *chris 
        age:
        - *thinkpad