keys:
  - &users:
    - &chris DB9ADBBE6FBD1F0E694AF25D012321D46E090E61 # public gpg key fingerprint
  - &hosts:
    - &thinkpad age1gyjvseqm77eqvuqah88d7j3a3acne069q4smcdcdxqec3df223rs47e7al # public age key converted from ssh public ed25519 key in /etc/ssh

creation_rules: # when sops creates/edits a secrets.yaml file it encrypts using both gpg and age public keys and one or the other corresponding private keys will be required to decrypt
  - path_regex: secrets.(yaml|json|env|ini)$ 
    key_groups:
      - pgp:
        - *chris 
        age:
        - *thinkpad

# host-specific age keys (derived from ssh key in /etc/ssh) are stale after new installation, so must 
# 1) re-run ssh-to-age on new host ssh public key using 'nix-shell -p ssh-to-age --run 'cat /etc/ssh/ssh_host_ed25519_key.pub | ssh-to-age'', 
# 2) copy new age public key into this .sops.yaml file, and 
# 3) run 'sops updatekeys /home/chris/nixos-configs/secrets.yaml' on the encrypted secrets file to update with new host encryption