{ pkgs, 
  lib, 
  ... 
}:

{

  services = {
    stirling-pdf = {
      enable = true;
      environment = {
        SERVER_PORT = 16237;
      };
    };
  };

  #virtualisation.oci-containers.containers = {
  #  stirling-pdf = {
  #    image = "docker.io/frooodle/s-pdf:0.18.1";
  #    autoStart = true;
  #    ports = [
  #      "16237:8080/tcp"
  #    ];
  #  };
  #  #log-driver = "journald";
  #  #extraOptions = [
  #  #  "--network-alias=stirling-pdf"
  #  #  "--network=backend"
  #  #];
  #};

  #systemd.services."podman-stirling-pdf" = {
  #  serviceConfig = {
  #    Restart = lib.mkOverride 90 "always";
  #  };
  #  partOf = [
  #    "podman-compose-stirlingpdf-root.target"
  #  ];
  #  wantedBy = [
  #    "podman-compose-stirlingpdf-root.target"
  #  ];
  #};

  #systemd.targets."podman-compose-stirlingpdf-root" = {
  #  unitConfig = {
  #    Description = "Root target generated by compose2nix.";
  #  };
  #  wantedBy = [ "multi-user.target" ];
  #};
  
}
