{
  pkgs,
  lib,
  config,
  configVars,
  ...
}:

let
  app = "fava";

  # one base for both addresses of the same location: filesystem for fava and
  # bean-price, nextcloud-internal for occ
  ncUser = "Chris Bond";
  ledgerRel = "files/Bond Family/Financial/bond-ledger";
  ledgerDir = "/var/lib/nextcloud/data/${ncUser}/${ledgerRel}";
  occPath = "/${ncUser}/${ledgerRel}/outside-balances";

  # fava plus its extensions in one python env; dashboards config is dashboards.yaml at the ledger root
  favaEnv = pkgs.python3.withPackages (ps: with ps; [
    fava
    fava-dashboards
  ]);

  # bean-check, for validating what bean-price writes
  beancountEnv = pkgs.python3.withPackages (ps: with ps; [ beancount ]);
in

{

  systemd.services.${app} = {
    description = "fava web interface for beancount";
    wantedBy = ["multi-user.target"];
    after = ["network.target"];
    environment = {
      BEANCOUNT_FILE = "${ledgerDir}/master.beancount";
    };
    serviceConfig = {
      # --read-only disables the editor, entry forms, and every write endpoint;
      # ledger edits are made in the beancount files directly, never through fava
      ExecStart = "${favaEnv}/bin/fava --host 127.0.0.1 --port 7191 --read-only";
      # nextcloud owns the ledger; no supplementary group needed to read it
      User = "nextcloud";
      Group = "nextcloud";
      Restart = "always";
      RestartSec = "5s";
      # no ReadWritePaths - the whole filesystem is read-only to this unit
      ProtectSystem = "strict";
      ProtectHome = true;
      PrivateTmp = true;
      PrivateDevices = true;
      NoNewPrivileges = true;
      RestrictSUIDSGID = true;
      RestrictAddressFamilies = ["AF_INET" "AF_INET6"];
      SystemCallFilter = ["@system-service"];
      LockPersonality = true;
    };
  };

  # fava never fetches prices; it renders the price directives in the ledger.
  # without a current mark, at_value silently falls back to cost.
  systemd.services."${app}-prices" = {
    description = "fetch market prices into the beancount ledger";
    after = [ "network-online.target" "nextcloud-setup.service" ];
    wants = [ "network-online.target" ];
    # no wantedBy: fired by the timer only

    path = [
      pkgs.beanprice # bean-price
      beancountEnv # bean-check
      pkgs.coreutils
      pkgs.gawk
    ];

    script = ''
      set -euo pipefail

      ledger="${ledgerDir}/master.beancount"
      outdir="${ledgerDir}/outside-balances"
      tmp="$(mktemp)"
      trap 'rm -f "$tmp"' EXIT

      # --update is incremental and emits nothing when current, so re-runs
      # never duplicate
      bean-price --update --update-rate weekly "$ledger" > "$tmp"

      if [ ! -s "$tmp" ]; then
        echo "prices already current; nothing written"
        exit 0
      fi

      # file by each directive's own date, not today's - a run straddling
      # 1 January emits december dates
      for year in $(awk '/^[0-9][0-9][0-9][0-9]-/ { print substr($1, 1, 4) }' "$tmp" | sort -u); do
        f="$outdir/prices-$year.beancount"
        [ -e "$f" ] || printf '; Machine-generated by the bean-price timer on aspen. Do not hand-edit.\n\n' > "$f"
      done

      awk -v d="$outdir" '
        /^[0-9][0-9][0-9][0-9]-/ { print >> (d "/prices-" substr($1, 1, 4) ".beancount"); n++ }
        END { printf "wrote %d price directive(s)\n", n }
      ' "$tmp"

      # master globs prices-*.beancount, so a new year file needs no include
      bean-check "$ledger"

      # the ledger sits in nextcloud's data dir; without a rescan the clients
      # never see the write and would clobber it on their next upload.
      # occ files:scan exits 0 on a bad path and reports failure only in its
      # Errors column, so parse the table rather than trusting the exit code.
      set +e
      scan_out="$(${lib.getExe config.services.nextcloud.occ} files:scan --path="${occPath}" 2>&1)"
      scan_rc=$?
      set -e
      printf '%s\n' "$scan_out"

      if [ "$scan_rc" -ne 0 ]; then
        echo "occ files:scan exited $scan_rc" >&2
        exit 1
      fi

      scan_errors="$(printf '%s\n' "$scan_out" \
        | awk -F'|' '/^\|/ && $2 ~ /^ *[0-9]+ *$/ { gsub(/ /, "", $7); print $7 }')"
      if [ "''${scan_errors:-}" != "0" ]; then
        echo "occ files:scan reported Errors=''${scan_errors:-unparsed}; nextcloud metadata is stale" >&2
        exit 1
      fi
    '';

    serviceConfig = {
      Type = "oneshot";
      # own the tree, so written files keep nextcloud:nextcloud
      User = "nextcloud";
      Group = "nextcloud";

      # "full", not "strict" as on the fava unit: occ writes under /var/lib
      ProtectSystem = "full";
      ProtectHome = true;
      PrivateTmp = true;
      PrivateDevices = true;
      NoNewPrivileges = true;
      RestrictSUIDSGID = true;
      LockPersonality = true;
      # INET for the quote fetch, UNIX for nextcloud's db and redis sockets
      RestrictAddressFamilies = [ "AF_INET" "AF_INET6" "AF_UNIX" ];
      SystemCallFilter = [ "@system-service" ];
    };
  };

  systemd.timers."${app}-prices" = {
    description = "weekly market price refresh for the beancount ledger";
    wantedBy = [ "timers.target" ];
    timerConfig = {
      # saturday, so the quote is friday's close
      OnCalendar = "Sat *-*-* 05:00:00";
      RandomizedDelaySec = "30m";
      Persistent = true; # catch up after downtime
      Unit = "${app}-prices.service";
    };
  };

  services.traefik.dynamicConfigOptions.http = {
    routers = {
      ${app} = {
        entrypoints = ["websecure"];
        rule = "Host(`bond-ledger.${configVars.domain2}`)";
        service = "${app}";
        middlewares = [
          "maintenance-page"
          "trusted-allow"
          "secure-headers"
          "forbidden-page"
        ];
        tls = {
          certResolver = "cloudflareDns";
          options = "tls-13@file";
        };
      };
    };
    services = {
      ${app} = {
        loadBalancer = {
          serversTransport = "default";
          passHostHeader = true;
          servers = [
          {
            url = "http://127.0.0.1:7191";
          }
          ];
        };
      };
    };
  };

}
