{
  pkgs,
  lib,
  config,
  configVars,
  ...
}:

let
  app = "fava";

  # the ledger lives inside nextcloud's data directory, so the same location has
  # two addresses: a filesystem path (what fava and bean-price use) and a
  # nextcloud-internal path (what occ uses). derive both from one base so they
  # cannot drift apart.
  ncUser = "Chris Bond";
  ledgerRel = "files/Bond Family/Financial/bond-ledger";
  ledgerDir = "/var/lib/nextcloud/data/${ncUser}/${ledgerRel}";
  occPath = "/${ncUser}/${ledgerRel}/outside-balances";

  # fava plus its extensions in one python env; dashboards config is dashboards.yaml at the ledger root
  favaEnv = pkgs.python3.withPackages (ps: with ps; [
    fava
    fava-dashboards
  ]);

  # beancount supplies bean-check for post-write validation; beanprice is a
  # separate top-level package and is not in python3Packages
  beancountEnv = pkgs.python3.withPackages (ps: with ps; [ beancount ]);
in

{

  systemd.services.${app} = {
    description = "fava web interface for beancount";
    wantedBy = ["multi-user.target"];
    after = ["network.target"];
    environment = {
      BEANCOUNT_FILE = "${ledgerDir}/master.beancount";
    };
    serviceConfig = {
      # --read-only disables the editor, entry forms, and every write endpoint;
      # ledger edits are made in the beancount files directly, never through fava
      ExecStart = "${favaEnv}/bin/fava --host 127.0.0.1 --port 7191 --read-only";
      # nextcloud owns the ledger; no supplementary group needed to read it
      User = "nextcloud";
      Group = "nextcloud";
      Restart = "always";
      RestartSec = "5s";
      # no ReadWritePaths - the whole filesystem is read-only to this unit
      ProtectSystem = "strict";
      ProtectHome = true;
      PrivateTmp = true;
      PrivateDevices = true;
      NoNewPrivileges = true;
      RestrictSUIDSGID = true;
      RestrictAddressFamilies = ["AF_INET" "AF_INET6"];
      SystemCallFilter = ["@system-service"];
      LockPersonality = true;
    };
  };

  # ---------------------------------------------------------------------------
  # Weekly market price refresh
  #
  # Beancount has no live pricing and no plugin that fetches market data - a
  # ledger is a static text file and `price` directives are data, not queries.
  # Fava renders whatever price directives exist at load and never fetches. So
  # "current market value" means exactly how recently this timer last ran.
  #
  # This matters because the PNC Roth IRA is carried at COST (it tracks
  # individual lots), and fava's at_value conversion silently falls back to cost
  # when no price exists at or before the report date - no warning, no
  # "unconverted" marker, just a number ~$100k low that looks entirely
  # plausible. Price marks are load-bearing, not cosmetic.
  # ---------------------------------------------------------------------------
  systemd.services."${app}-prices" = {
    description = "fetch market prices into the beancount ledger";
    after = [ "network-online.target" "nextcloud-setup.service" ];
    wants = [ "network-online.target" ];
    # no wantedBy: fired by the timer only

    path = [
      pkgs.beanprice # bean-price
      beancountEnv # bean-check
      pkgs.coreutils
      pkgs.gawk
    ];

    script = ''
      set -euo pipefail

      ledger="${ledgerDir}/master.beancount"
      outdir="${ledgerDir}/outside-balances"
      tmp="$(mktemp)"
      trap 'rm -f "$tmp"' EXIT

      # --update walks forward from each commodity's newest existing price and
      # emits nothing when everything is current, so repeat runs never
      # duplicate. It also prices only the intervals a commodity was actually
      # held, so sold positions stop accumulating quotes by themselves.
      bean-price --update --update-rate weekly "$ledger" > "$tmp"

      if [ ! -s "$tmp" ]; then
        echo "prices already current; nothing written"
        exit 0
      fi

      # A run that straddles 1 January emits December dates. Route every
      # directive to the year file its own date belongs to, not to today's year.
      for year in $(awk '/^[0-9][0-9][0-9][0-9]-/ { print substr($1, 1, 4) }' "$tmp" | sort -u); do
        f="$outdir/prices-$year.beancount"
        [ -e "$f" ] || printf '; Machine-generated by the bean-price timer on aspen. Do not hand-edit.\n\n' > "$f"
      done

      awk -v d="$outdir" '
        /^[0-9][0-9][0-9][0-9]-/ { print >> (d "/prices-" substr($1, 1, 4) ".beancount"); n++ }
        END { printf "wrote %d price directive(s)\n", n }
      ' "$tmp"

      # master.beancount globs prices-*.beancount, so a brand new year file is
      # picked up with no include line to edit. Parse the result and fail loudly
      # if it broke - bad data then sits on disk for inspection instead of being
      # served as though it were good.
      bean-check "$ledger"

      # The ledger lives inside nextcloud's data directory. Writing here out of
      # band leaves nextcloud's database holding stale metadata: the desktop
      # clients never receive the new prices, and the next client-side upload of
      # this path would clobber them. A scoped rescan keeps the two in step.
      #
      # occ files:scan EXITS 0 EVEN WHEN THE PATH IS WRONG - it reports the
      # failure only as a non-zero Errors column in its summary table. Verified
      # against a deliberately bad path. So parse the table; without this the
      # unit would report success while the clients silently fell behind.
      set +e
      scan_out="$(${lib.getExe config.services.nextcloud.occ} files:scan --path="${occPath}" 2>&1)"
      scan_rc=$?
      set -e
      printf '%s\n' "$scan_out"

      if [ "$scan_rc" -ne 0 ]; then
        echo "occ files:scan exited $scan_rc" >&2
        exit 1
      fi

      scan_errors="$(printf '%s\n' "$scan_out" \
        | awk -F'|' '/^\|/ && $2 ~ /^ *[0-9]+ *$/ { gsub(/ /, "", $7); print $7 }')"
      if [ "''${scan_errors:-}" != "0" ]; then
        echo "occ files:scan reported Errors=''${scan_errors:-unparsed}; nextcloud metadata is stale" >&2
        exit 1
      fi
    '';

    serviceConfig = {
      Type = "oneshot";
      # write as the owner of the tree so synced files keep nextcloud:nextcloud
      User = "nextcloud";
      Group = "nextcloud";

      # ProtectSystem is "full", not "strict" as on the fava unit: occ writes to
      # nextcloud's config, cache and logs under /var/lib, and enumerating those
      # as ReadWritePaths would silently rot as upstream moves them.
      ProtectSystem = "full";
      ProtectHome = true;
      PrivateTmp = true;
      PrivateDevices = true;
      NoNewPrivileges = true;
      RestrictSUIDSGID = true;
      LockPersonality = true;
      # INET for the quote fetch; UNIX for nextcloud's database and redis sockets
      RestrictAddressFamilies = [ "AF_INET" "AF_INET6" "AF_UNIX" ];
      SystemCallFilter = [ "@system-service" ];
    };
  };

  systemd.timers."${app}-prices" = {
    description = "weekly market price refresh for the beancount ledger";
    wantedBy = [ "timers.target" ];
    timerConfig = {
      # Saturday: the markets are shut, so the quote is Friday's close and will
      # not shift under a reader partway through the weekend.
      OnCalendar = "Sat *-*-* 05:00:00";
      RandomizedDelaySec = "30m";
      Persistent = true; # catch up after downtime instead of skipping a week
      Unit = "${app}-prices.service";
    };
  };

  services.traefik.dynamicConfigOptions.http = {
    routers = {
      ${app} = {
        entrypoints = ["websecure"];
        rule = "Host(`bond-ledger.${configVars.domain2}`)";
        service = "${app}";
        middlewares = [
          "maintenance-page"
          "trusted-allow"
          "secure-headers"
          "forbidden-page"
        ];
        tls = {
          certResolver = "cloudflareDns";
          options = "tls-13@file";
        };
      };
    };
    services = {
      ${app} = {
        loadBalancer = {
          serversTransport = "default";
          passHostHeader = true;
          servers = [
          {
            url = "http://127.0.0.1:7191";
          }
          ];
        };
      };
    };
  };

}
