live_config_reload = true
#"window.dynamic_title" = true

[colors.bright]
black = "0x4C566A"
blue = "0x81A1C1"
cyan = "0x8FBCBB"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xECEFF4"
yellow = "0xEBCB8B"

[colors.normal]
black = "0x3B4252"
blue = "0x81A1C1"
cyan = "0x88C0D0"
green = "0xA3BE8C"
magenta = "0xB48EAD"
red = "0xBF616A"
white = "0xE5E9F0"
yellow = "0xEBCB8B"

[colors.primary]
background = "0x2E3440"
foreground = "0xD8DEE9"

[cursor]
style = "Block"

[debug]
log_level = "DEBUG"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "alacritty"

[font]
size = 12.0

[font.bold]
family = "SauceCodePro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "SauceCodePro Nerd Font"
style = "Semibold Italic"

[font.italic]
family = "SauceCodePro Nerd Font"
style = "Italic"

[font.normal]
family = "SauceCodePro Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Shift|Control"

[scrolling]
history = 2048
multiplier = 3

[selection]
save_to_clipboard = false

[window]
opacity = 0.8
