{ pkgs, 
  lib, 
  ... 
}:

{
  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
    defaultNetwork.settings = {
      # Required for container networking to be able to use names.
      dns_enabled = true;
    };
  };

  # Enable container name DNS for non-default Podman networks.
  # https://github.com/NixOS/nixpkgs/issues/226365
  networking.firewall.interfaces."podman+".allowedUDPPorts = [ 53 ];

  virtualisation.oci-containers.backend = "podman";

  # Containers
  virtualisation.oci-containers.containers."stirling-pdf" = {
    image = "docker.io/frooodle/s-pdf:0.18.1";
    ports = [
      "16237:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=stirling-pdf"
      "--network=backend"
    ];
  };
  systemd.services."podman-stirling-pdf" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    partOf = [
      "podman-compose-stirlingpdf-root.target"
    ];
    wantedBy = [
      "podman-compose-stirlingpdf-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."podman-compose-stirlingpdf-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
